version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: fundonkdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
